# Generated by Django 5.2.14 on 2026-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("nombre_comercial", models.CharField(blank=True, max_length=200)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("RUC", "RUC"),
                            ("DNI", "DNI"),
                            ("CE", "CE"),
                            ("OTRO", "Otro"),
                        ],
                        default="RUC",
                        max_length=10,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=30, unique=True)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("direccion", models.TextField(blank=True)),
                ("sitio_web", models.URLField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["razon_social"],
            },
        ),
    ]
